require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SprojectsController do

  # This should return the minimal set of attributes required to create a valid
  # Sproject. As you add validations to Sproject, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SprojectsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sprojects as @sprojects" do
      sproject = Sproject.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sprojects).should eq([sproject])
    end
  end

  describe "GET show" do
    it "assigns the requested sproject as @sproject" do
      sproject = Sproject.create! valid_attributes
      get :show, {:id => sproject.to_param}, valid_session
      assigns(:sproject).should eq(sproject)
    end
  end

  describe "GET new" do
    it "assigns a new sproject as @sproject" do
      get :new, {}, valid_session
      assigns(:sproject).should be_a_new(Sproject)
    end
  end

  describe "GET edit" do
    it "assigns the requested sproject as @sproject" do
      sproject = Sproject.create! valid_attributes
      get :edit, {:id => sproject.to_param}, valid_session
      assigns(:sproject).should eq(sproject)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Sproject" do
        expect {
          post :create, {:sproject => valid_attributes}, valid_session
        }.to change(Sproject, :count).by(1)
      end

      it "assigns a newly created sproject as @sproject" do
        post :create, {:sproject => valid_attributes}, valid_session
        assigns(:sproject).should be_a(Sproject)
        assigns(:sproject).should be_persisted
      end

      it "redirects to the created sproject" do
        post :create, {:sproject => valid_attributes}, valid_session
        response.should redirect_to(Sproject.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sproject as @sproject" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sproject.any_instance.stub(:save).and_return(false)
        post :create, {:sproject => { "name" => "invalid value" }}, valid_session
        assigns(:sproject).should be_a_new(Sproject)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sproject.any_instance.stub(:save).and_return(false)
        post :create, {:sproject => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sproject" do
        sproject = Sproject.create! valid_attributes
        # Assuming there are no other sprojects in the database, this
        # specifies that the Sproject created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Sproject.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => sproject.to_param, :sproject => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested sproject as @sproject" do
        sproject = Sproject.create! valid_attributes
        put :update, {:id => sproject.to_param, :sproject => valid_attributes}, valid_session
        assigns(:sproject).should eq(sproject)
      end

      it "redirects to the sproject" do
        sproject = Sproject.create! valid_attributes
        put :update, {:id => sproject.to_param, :sproject => valid_attributes}, valid_session
        response.should redirect_to(sproject)
      end
    end

    describe "with invalid params" do
      it "assigns the sproject as @sproject" do
        sproject = Sproject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sproject.any_instance.stub(:save).and_return(false)
        put :update, {:id => sproject.to_param, :sproject => { "name" => "invalid value" }}, valid_session
        assigns(:sproject).should eq(sproject)
      end

      it "re-renders the 'edit' template" do
        sproject = Sproject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sproject.any_instance.stub(:save).and_return(false)
        put :update, {:id => sproject.to_param, :sproject => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sproject" do
      sproject = Sproject.create! valid_attributes
      expect {
        delete :destroy, {:id => sproject.to_param}, valid_session
      }.to change(Sproject, :count).by(-1)
    end

    it "redirects to the sprojects list" do
      sproject = Sproject.create! valid_attributes
      delete :destroy, {:id => sproject.to_param}, valid_session
      response.should redirect_to(sprojects_url)
    end
  end

end
